# VERIFICA COLONNE DATI ISTAT

In [4]:
import pandas as pd

In [5]:
df_istat = pd.read_csv("../raw_data/ISTAT_raw.csv")
print(df_istat.dtypes)

DATAFLOW                str
FREQ                    str
REF_AREA              int64
DATA_TYPE               str
RESULT                  str
TIME_PERIOD           int64
OBS_VALUE             int64
OBS_STATUS          float64
NOTE_DS             float64
NOTE_REF_AREA       float64
NOTE_DATA_TYPE      float64
NOTE_RESULT         float64
NOTE_TIME_PERIOD    float64
BASE_PER            float64
UNIT_MEAS           float64
UNIT_MULT           float64
dtype: object

# DATAFLOW (str)
"IT1:41_983(1.0)", probabilmente inutile

In [ ]:
print(df_istat["DATAFLOW"].unique())
print("________________________________________________")
print(df_istat["DATAFLOW"].value_counts())
print("________________________________________________")
print("Valori nulli: ", df_istat["DATAFLOW"].isnull().sum())
print("________________________________________________")

# FREQ (str)
"A", probabilmente inutile

In [ ]:
print(df_istat["FREQ"].unique())
print("________________________________________________")
print(df_istat["FREQ"].value_counts())
print("________________________________________________")
print("Valori nulli: ", df_istat["FREQ"].isnull().sum())
print("________________________________________________")

# REF_AREA (int64)
valori da 1001 a 111107, indicano comuni ma da verificare tra gli anni cosa cambia

In [ ]:
print(df_istat["REF_AREA"].unique())
print("________________________________________________")
print(df_istat["REF_AREA"].value_counts())
print("________________________________________________")
print("Valori nulli: ", df_istat["REF_AREA"].isnull().sum())
print("________________________________________________")

# DATA_TYPE (str)
le due possibilita' della colonna "DATA TYPE" sono:
-KILLINJ , kill injuries? morti?
-ROADACC, road accident? incidenti stradali?

da verificare

In [ ]:
print(df_istat["DATA_TYPE"].unique())
print("________________________________________________")
print(df_istat["DATA_TYPE"].value_counts())
print("________________________________________________")
print("Valori nulli: ", df_istat["DATA_TYPE"].isnull().sum())
print("________________________________________________")

# RESULT (str)
F,M, 9 indicano il genere? se si, cosa cazzo e' 9? bambini?
33%, 33%, 33%

In [ ]:
print(df_istat["RESULT"].unique())
print("________________________________________________")
print(df_istat["RESULT"].value_counts())
print("________________________________________________")
print("Valori nulli: ", df_istat["RESULT"].isnull().sum())
print("________________________________________________")

# TIME PERIOD (int64)
Da 2001 a 2024, il numero decresce da 24306 a 23712, meno comuni?

In [ ]:
print(df_istat["TIME_PERIOD"].unique())
print("________________________________________________")
print(df_istat["TIME_PERIOD"].value_counts())
print("________________________________________________")
print("Valori nulli: ", df_istat["TIME_PERIOD"].isnull().sum())
print("________________________________________________")

# OBS_VALUE (int64)
numero di incidenti? non sono in ordine ordinato, da capire perche'.
quasi 50% del totale e' 0.

In [10]:
print(df_istat["OBS_VALUE"].unique())
print("________________________________________________")
print(df_istat["OBS_VALUE"].value_counts())
print("________________________________________________")
print("Valori nulli: ", df_istat["OBS_VALUE"].isnull().sum())
print("________________________________________________")
print(df_istat["OBS_VALUE"].describe())

[  10    7   13 ... 1081  880  969]
________________________________________________
OBS_VALUE
0       228506
1        69233
2        39073
3        26988
4        20725
         ...
1449         1
1460         1
1081         1
880          1
969          1
Name: count, Length: 1830, dtype: int64
________________________________________________
Valori nulli:  0
________________________________________________
count    573552.000000
mean         20.207603
std         245.813966
min           0.000000
25%           0.000000
50%           1.000000
75%           8.000000
max       30254.000000
Name: OBS_VALUE, dtype: float64

# OBS_STATUS (float64)

Tutti Nulli

In [ ]:
print(df_istat["OBS_STATUS"].unique())
print("________________________________________________")
print(df_istat["OBS_STATUS"].value_counts())
print("________________________________________________")
print("Valori nulli: ", df_istat["OBS_STATUS"].isnull().sum())
print("________________________________________________")
print(df_istat["OBS_STATUS"].describe())

[nan]
________________________________________________
Series([], Name: count, dtype: int64)
________________________________________________
Valori nulli:  573552
________________________________________________
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: OBS_STATUS, dtype: float64

# NOTE_* (float64)

sono tutti Nan

In [56]:
print("NOTE_DS:")
print(df_istat["NOTE_DS"].unique())
print(df_istat["NOTE_DS"].isna().sum())
print("________________________________________________")

print("NOTE_REF_AREA:")
print(df_istat["NOTE_REF_AREA"].unique())
print(df_istat["NOTE_REF_AREA"].isna().sum())
print("________________________________________________")

print("NOTE_DATA_TYPE:")
print(df_istat["NOTE_DATA_TYPE"].unique())
print(df_istat["NOTE_DATA_TYPE"].isna().sum())
print("________________________________________________")

print("NOTE_RESULT:")
print(df_istat["NOTE_RESULT"].unique())
print(df_istat["NOTE_RESULT"].isna().sum())
print("________________________________________________")

print("NOTE_TIME_PERIOD:")
print(df_istat["NOTE_TIME_PERIOD"].unique())
print(df_istat["NOTE_TIME_PERIOD"].isna().sum())
print("________________________________________________")

NOTE_DS:
[nan]
573552
________________________________________________
NOTE_REF_AREA:
[nan]
573552
________________________________________________
NOTE_DATA_TYPE:
[nan]
573552
________________________________________________
NOTE_RESULT:
[nan]
573552
________________________________________________
NOTE_TIME_PERIOD:
[nan]
573552
________________________________________________

# ALTRE COLONNE (float64)

sono tutti Nan

In [58]:
print("BASE_PER:")
print(df_istat["BASE_PER"].unique())
print(df_istat["BASE_PER"].isna().sum())
print("________________________________________________")

print("UNIT_MEAS:")
print(df_istat["UNIT_MEAS"].unique())
print(df_istat["UNIT_MEAS"].isna().sum())
print("________________________________________________")

print("UNIT_MULT:")
print(df_istat["UNIT_MULT"].unique())
print(df_istat["UNIT_MULT"].isna().sum())
print("________________________________________________")

BASE_PER:
[nan]
573552
________________________________________________
UNIT_MEAS:
[nan]
573552
________________________________________________
UNIT_MULT:
[nan]
573552
________________________________________________

# VERIFICA COLONNE DATI SITUAS

In [5]:
df_2024 = pd.read_csv("../raw_data/comuni_2024-12-31.csv", sep=";")
df_2026 = pd.read_csv("../raw_data/comuni_2026-06-21.csv", sep=";")

In [11]:
print(df_2024.columns)
print("_______________________________________")
print(df_2026.columns)

Index(['Codice Ripartizione geografica', 'Codice Regione',
       'Codice Provincia (Storico)', 'Codice Provincia/Uts',
       'Codice Comune (alfanumerico)', 'Codice Comune (numerico)', 'Comune',
       'Comune (dizione straniera)', 'Sigla automobilistica',
       'Capoluogo di Provincia/Uts', 'Capoluogo di Regione',
       'Popolazione legale', 'Anno Censimento', 'Superficie (Kmq)',
       'Anno (Superficie)', 'Popolazione residente',
       'Anno (Popolazione residente)'],
      dtype='str')
_______________________________________
Index(['Codice Ripartizione geografica', 'Codice Regione',
       'Codice Provincia (Storico)', 'Codice Provincia/Uts',
       'Codice Comune (alfanumerico)', 'Codice Comune (numerico)', 'Comune',
       'Comune (dizione straniera)', 'Sigla automobilistica',
       'Capoluogo di Provincia/Uts', 'Capoluogo di Regione',
       'Popolazione legale', 'Anno Censimento', 'Superficie (Kmq)',
       'Anno (Superficie)', 'Popolazione residente',
       'Anno (Popolazione residente)'],
      dtype='str')

In [12]:
print(df_2024.dtypes)
print("_______________________________________")
print(df_2026.dtypes)

Codice Ripartizione geografica    int64
Codice Regione                    int64
Codice Provincia (Storico)        int64
Codice Provincia/Uts              int64
Codice Comune (alfanumerico)      int64
Codice Comune (numerico)          int64
Comune                              str
Comune (dizione straniera)          str
Sigla automobilistica               str
Capoluogo di Provincia/Uts        int64
Capoluogo di Regione              int64
Popolazione legale                int64
Anno Censimento                   int64
Superficie (Kmq)                    str
Anno (Superficie)                 int64
Popolazione residente             int64
Anno (Popolazione residente)      int64
dtype: object
_______________________________________
Codice Ripartizione geografica    int64
Codice Regione                    int64
Codice Provincia (Storico)        int64
Codice Provincia/Uts              int64
Codice Comune (alfanumerico)      int64
Codice Comune (numerico)          int64
Comune                              str
Comune (dizione straniera)          str
Sigla automobilistica               str
Capoluogo di Provincia/Uts        int64
Capoluogo di Regione              int64
Popolazione legale                int64
Anno Censimento                   int64
Superficie (Kmq)                    str
Anno (Superficie)                 int64
Popolazione residente             int64
Anno (Popolazione residente)      int64
dtype: object

# DIFFERENZE TRA 2026 E 2024

In [17]:
print("comuni presenti 2024: ", len(df_2024))
print("comuni presenti 2026: ", len(df_2026))
print("differenza numerica: ", len(df_2026)-len(df_2024), " comuni nel 2026")

comuni presenti 2024:  7896
comuni presenti 2026:  7894
differenza numerica:  -2  comuni nel 2026

Considerando il periodo dello storico dati che si ferma al 2024 ma volendo evitare di fare operazioni su comuni che non esistono pie' trovo i comuni in comune tra il 2024 e oggi con inner join

In [26]:
df_comuni_2426 = df_2024.merge(df_2026, how="inner", on="Codice Comune (numerico)").reset_index(drop=True)

print("Comuni presenti sia nel 2024 che nel 2026: ", len(df_comuni_2426))

Comuni presenti sia nel 2024 che nel 2026:  7516

In [30]:
print(df_comuni_2426.shape)
print("________________________________")
print(df_comuni_2426.head(10))

(7516, 33)
________________________________
   Codice Ripartizione geografica_x  Codice Regione_x  \
0                                 1                 1
1                                 1                 1
2                                 1                 1
3                                 1                 1
4                                 1                 1
5                                 1                 1
6                                 1                 1
7                                 1                 1
8                                 1                 1
9                                 1                 1

   Codice Provincia (Storico)_x  Codice Provincia/Uts_x  \
0                             1                     201
1                             1                     201
2                             1                     201
3                             1                     201
4                             1                     201
5                             1                     201
6                             1                     201
7                             1                     201
8                             1                     201
9                             1                     201

   Codice Comune (alfanumerico)_x  Codice Comune (numerico)         Comune_x  \
0                            1001                      1001            Agliè
1                            1002                      1002          Airasca
2                            1003                      1003     Ala di Stura
3                            1004                      1004  Albiano d'Ivrea
4                            1006                      1006           Almese
5                            1007                      1007          Alpette
6                            1008                      1008        Alpignano
7                            1009                      1009         Andezeno
8                            1010                      1010          Andrate
9                            1011                      1011         Angrogna

  Comune (dizione straniera)_x Sigla automobilistica_x  \
0                          NaN                      TO
1                          NaN                      TO
2                          NaN                      TO
3                          NaN                      TO
4                          NaN                      TO
5                          NaN                      TO
6                          NaN                      TO
7                          NaN                      TO
8                          NaN                      TO
9                          NaN                      TO

   Capoluogo di Provincia/Uts_x  ...  Comune (dizione straniera)_y  \
0                             0  ...                           NaN
1                             0  ...                           NaN
2                             0  ...                           NaN
3                             0  ...                           NaN
4                             0  ...                           NaN
5                             0  ...                           NaN
6                             0  ...                           NaN
7                             0  ...                           NaN
8                             0  ...                           NaN
9                             0  ...                           NaN

   Sigla automobilistica_y  Capoluogo di Provincia/Uts_y  \
0                       TO                             0
1                       TO                             0
2                       TO                             0
3                       TO                             0
4                       TO                             0
5                       TO                             0
6                       TO                             0
7                       TO                             0
8                       TO                             0
9                       TO                             0

  Capoluogo di Regione_y  Popolazione legale_y  Anno Censimento_y  \
0                      0                  2562               2021
1                      0                  3660               2021
2                      0                   467               2021
3                      0                  1637               2021
4                      0                  6331               2021
5                      0                   240               2021
6                      0                 16501               2021
7                      0                  2036               2021
8                      0                   474               2021
9                      0                   827               2021

   Superficie (Kmq)_y  Anno (Superficie)_y  Popolazione residente_y  \
0             13,1463                 2026                     2585
1             15,7393                 2026                     3695
2             46,3316                 2026                      463
3             11,7397                 2026                     1624
4             17,8741                 2026                     6297
5              5,6311                 2026                      248
6             11,9193                 2026                    16494
7              7,4859                 2026                     1995
8              9,3090                 2026                      466
9             38,8781                 2026                      804

   Anno (Popolazione residente)_y
0                            2024
1                            2024
2                            2024
3                            2024
4                            2024
5                            2024
6                            2024
7                            2024
8                            2024
9                            2024

[10 rows x 33 columns]

In [31]:
print(df_comuni_2426.columns)

Index(['Codice Ripartizione geografica_x', 'Codice Regione_x',
       'Codice Provincia (Storico)_x', 'Codice Provincia/Uts_x',
       'Codice Comune (alfanumerico)_x', 'Codice Comune (numerico)',
       'Comune_x', 'Comune (dizione straniera)_x', 'Sigla automobilistica_x',
       'Capoluogo di Provincia/Uts_x', 'Capoluogo di Regione_x',
       'Popolazione legale_x', 'Anno Censimento_x', 'Superficie (Kmq)_x',
       'Anno (Superficie)_x', 'Popolazione residente_x',
       'Anno (Popolazione residente)_x', 'Codice Ripartizione geografica_y',
       'Codice Regione_y', 'Codice Provincia (Storico)_y',
       'Codice Provincia/Uts_y', 'Codice Comune (alfanumerico)_y', 'Comune_y',
       'Comune (dizione straniera)_y', 'Sigla automobilistica_y',
       'Capoluogo di Provincia/Uts_y', 'Capoluogo di Regione_y',
       'Popolazione legale_y', 'Anno Censimento_y', 'Superficie (Kmq)_y',
       'Anno (Superficie)_y', 'Popolazione residente_y',
       'Anno (Popolazione residente)_y'],
      dtype='str')

In [39]:
df_2426_clean = df_comuni_2426[[
    "Codice Ripartizione geografica_x",
    "Codice Regione_x",
    "Codice Provincia/Uts_x",
    "Codice Comune (alfanumerico)_x", 
    "Codice Comune (numerico)",
    "Comune_x",
    "Sigla automobilistica_x",
    "Capoluogo di Provincia/Uts_x",
    "Capoluogo di Regione_x",
    "Popolazione legale_x",
    "Anno Censimento_x",
    "Superficie (Kmq)_x",
    "Anno (Superficie)_x",
    "Popolazione residente_x",
    "Anno (Popolazione residente)_x"
    ]].copy()

In [40]:
df_2426_clean.columns = [
    "ID_Ripartizione_Geografica",
    "ID_Regione",
    "ID_Provincia/Uts",
    "IDA_Comune", 
    "IDN_Comune",
    "Comune",
    "Sigla_Auto",
    "IS_Capoluogo_Provincia/Uts",
    "IS_Capoluogo_Regione",
    "Pop_Legale",
    "Anno_Pop_Legale",
    "Superficie_Kmq",
    "Anno_Superficie",
    "Pop_Residente",
    "Anno_Pop_Residente"
]

print(df_2426_clean.dtypes)
df_2426_clean.head(3)

ID_Ripartizione_Geografica    int64
ID_Regione                    int64
ID_Provincia/Uts              int64
IDA_Comune                    int64
IDN_Comune                    int64
Comune                          str
Sigla_Auto                      str
IS_Capoluogo_Provincia/Uts    int64
IS_Capoluogo_Regione          int64
Pop_Legale                    int64
Anno_Pop_Legale               int64
Superficie_Kmq                  str
Anno_Superficie               int64
Pop_Residente                 int64
Anno_Pop_Residente            int64
dtype: object

,ID_Ripartizione_Geografica,ID_Regione,ID_Provincia/Uts,IDA_Comune,IDN_Comune,Comune,Sigla_Auto,IS_Capoluogo_Provincia/Uts,IS_Capoluogo_Regione,Pop_Legale,Anno_Pop_Legale,Superficie_Kmq,Anno_Superficie,Pop_Residente,Anno_Pop_Residente
0,1,1,201,1001,1001,Agliè,TO,0,0,2562,2021,"13,1463",2024,2585,2024
1,1,1,201,1002,1002,Airasca,TO,0,0,3660,2021,"15,7393",2024,3695,2024
2,1,1,201,1003,1003,Ala di Stura,TO,0,0,467,2021,"46,3316",2024,463,2024

In [41]:
df_2426_clean["Superficie_Kmq"] = df_2426_clean["Superficie_Kmq"].astype(str).str.replace(".", "", regex=False)
df_2426_clean["Superficie_Kmq"] = df_2426_clean["Superficie_Kmq"].astype(str).str.replace(",", ".", regex=False).astype(float)
print(df_2426_clean["Superficie_Kmq"].dtypes)

float64

In [42]:
print(df_2426_clean.dtypes)
df_2426_clean.head(3)

ID_Ripartizione_Geografica      int64
ID_Regione                      int64
ID_Provincia/Uts                int64
IDA_Comune                      int64
IDN_Comune                      int64
Comune                            str
Sigla_Auto                        str
IS_Capoluogo_Provincia/Uts      int64
IS_Capoluogo_Regione            int64
Pop_Legale                      int64
Anno_Pop_Legale                 int64
Superficie_Kmq                float64
Anno_Superficie                 int64
Pop_Residente                   int64
Anno_Pop_Residente              int64
dtype: object

,ID_Ripartizione_Geografica,ID_Regione,ID_Provincia/Uts,IDA_Comune,IDN_Comune,Comune,Sigla_Auto,IS_Capoluogo_Provincia/Uts,IS_Capoluogo_Regione,Pop_Legale,Anno_Pop_Legale,Superficie_Kmq,Anno_Superficie,Pop_Residente,Anno_Pop_Residente
0,1,1,201,1001,1001,Agliè,TO,0,0,2562,2021,13.1463,2024,2585,2024
1,1,1,201,1002,1002,Airasca,TO,0,0,3660,2021,15.7393,2024,3695,2024
2,1,1,201,1003,1003,Ala di Stura,TO,0,0,467,2021,46.3316,2024,463,2024

In [47]:
print(df_2426_clean.isnull().sum())

ID_Ripartizione_Geografica     0
ID_Regione                     0
ID_Provincia/Uts               0
IDA_Comune                     0
IDN_Comune                     0
Comune                         1
Sigla_Auto                    92
IS_Capoluogo_Provincia/Uts     0
IS_Capoluogo_Regione           0
Pop_Legale                     0
Anno_Pop_Legale                0
Superficie_Kmq                 0
Anno_Superficie                0
Pop_Residente                  0
Anno_Pop_Residente             0
dtype: int64

In [46]:
df_2426_clean[df_2426_clean["Comune"].isnull()].head()

,ID_Ripartizione_Geografica,ID_Regione,ID_Provincia/Uts,IDA_Comune,IDN_Comune,Comune,Sigla_Auto,IS_Capoluogo_Provincia/Uts,IS_Capoluogo_Regione,Pop_Legale,Anno_Pop_Legale,Superficie_Kmq,Anno_Superficie,Pop_Residente,Anno_Pop_Residente
164,1,1,201,1168,1168,NaN,TO,0,0,7830,2021,24.6422,2024,7662,2024

In [49]:
df_2426_clean[df_2426_clean["Sigla_Auto"].isnull()].head(92)

,ID_Ripartizione_Geografica,ID_Regione,ID_Provincia/Uts,IDA_Comune,IDN_Comune,Comune,Sigla_Auto,IS_Capoluogo_Provincia/Uts,IS_Capoluogo_Regione,Pop_Legale,Anno_Pop_Legale,Superficie_Kmq,Anno_Superficie,Pop_Residente,Anno_Pop_Residente
5053,4,15,263,63001,63001,Acerra,NaN,0,0,58494,2021,54.7117,2024,58676,2024
5054,4,15,263,63002,63002,Afragola,NaN,0,0,62198,2021,17.9149,2024,61786,2024
5055,4,15,263,63003,63003,Agerola,NaN,0,0,7666,2021,19.8316,2024,7760,2024
5056,4,15,263,63004,63004,Anacapri,NaN,0,0,6882,2021,6.3581,2024,6757,2024
5057,4,15,263,63005,63005,Arzano,NaN,0,0,32465,2021,4.7535,2024,31797,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5140,4,15,263,63088,63088,Visciano,NaN,0,0,4199,2021,10.9035,2024,4143,2024
5141,4,15,263,63089,63089,Volla,NaN,0,0,25369,2021,6.2162,2024,25936,2024
5142,4,15,263,63090,63090,Santa Maria la Carità,NaN,0,0,11689,2021,3.9788,2024,11788,2024
5143,4,15,263,63091,63091,Trecase,NaN,0,0,8594,2021,6.2619,2024,8580,2024
5144,4,15,263,63092,63092,Massa di Somma,NaN,0,0,5056,2021,3.0420,2024,4965,2024

i napoletani sono spariti lol